In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Создание датафреймов для каждого задания
data_1 = {
    'Y': [15, 18, 21, 22, 34, 36, 37],
    'X': [30, 28, 34, 38, 39, 45, 54]
}
data_2 = {
    'Y': [27, 32, 37, 40, 62, 66, 68],
    'X': [21.3, 20, 24, 26.7, 27.3, 31.3, 37.3]
}
data_3 = {
    'Y': [10, 13, 15, 17, 26, 28, 29],
    'X': [16, 15, 18, 20, 20.5, 23.5, 28]
}
data_4 = {
    'Y': [20, 24, 28, 30, 46.5, 49.5, 51],
    'X': [16, 15, 18, 20, 20.5, 23.5, 28]
}
data_5 = {
    'Y': [7, 8, 9, 10, 15.5, 16.5, 17],
    'X': [8, 7.5, 9, 10, 10.25, 11.75, 14]
}
data_6 = {
    'Y': [17, 20, 23, 25, 38.75, 41.25, 42.5],
    'X': [10.7, 10, 12, 13.3, 13.7, 15.7, 18.7]
}

# Конвертация в датафреймы
df1 = pd.DataFrame(data_1)
df2 = pd.DataFrame(data_2)
df3 = pd.DataFrame(data_3)
df4 = pd.DataFrame(data_4)
df5 = pd.DataFrame(data_5)
df6 = pd.DataFrame(data_6)

# Объединение всех датафреймов в один
all_data = pd.concat([df1, df2, df3, df4, df5, df6], ignore_index=True)

# Добавление фиктивной переменной Z
all_data['Z'] = [0 if i < 4 else 1 for i in range(all_data.shape[0])]

all_data.head()  # Просмотр первых нескольких строк объединенного датафрейма

      Y     X  Z
0  15.0  30.0  0
1  18.0  28.0  0
2  21.0  34.0  0
3  22.0  38.0  0
4  34.0  39.0  1

In [2]:
# Модель парной линейной регрессии Y от X
model_simple = LinearRegression()
model_simple.fit(all_data[['X']], all_data['Y'])

# Предсказание и расчет показателей качества для парной регрессии
y_pred_simple = model_simple.predict(all_data[['X']])
mse_simple = mean_squared_error(all_data['Y'], y_pred_simple)
r2_simple = r2_score(all_data['Y'], y_pred_simple)

# Модель множественной линейной регрессии Y от X и Z
model_multiple = LinearRegression()
model_multiple.fit(all_data[['X', 'Z']], all_data['Y'])

# Предсказание и расчет показателей качества для множественной регрессии
y_pred_multiple = model_multiple.predict(all_data[['X', 'Z']])
mse_multiple = mean_squared_error(all_data['Y'], y_pred_multiple)
r2_multiple = r2_score(all_data['Y'], y_pred_multiple)

# Вывод результатов
coefficients_simple = model_simple.coef_[0], model_simple.intercept_
coefficients_multiple = model_multiple.coef_, model_multiple.intercept_

(coefficients_simple, mse_simple, r2_simple), (coefficients_multiple, mse_multiple, r2_multiple)

(((0.7481270181486331, 12.317032526687111),
  174.1999032355637,
  0.2600652088772961),
 ((array([ 0.95963079, 22.06129586]), -12.188000833885607),
  137.15549840739308,
  0.4174157207873471))